'use client'

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import React, { useState, createContext } from 'react';
import "./globals.css";

export const ThemeContext = createContext(false);
export const ThemeUpdateContext = createContext<() => void>(() => {});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Job Chaser",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [darkTheme, setDarkTheme] = useState(false);

  function toggleTheme() {
      console.log('toggleTheme');
      setDarkTheme(prevDarkTheme => !prevDarkTheme);
  }

  const themeStyles = {
    backgroundColor: darkTheme ? '#333' : '#f5f5f5',
    color: darkTheme ? '#f5f5f5' : '#333',
  };

  return (
    <html lang="en">
      <ThemeContext.Provider value={darkTheme}>
        <ThemeUpdateContext.Provider value={toggleTheme}>
          <body
            style={themeStyles}
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
          >
            {children}
          </body>
        </ThemeUpdateContext.Provider>
      </ThemeContext.Provider>
    </html>
  );
}
